version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: content_bridge_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test 
    env_file:
      - ./Back-end/.env
    volumes:
      - postgres_:/var/lib/postgresql/data
    networks:
      - smm-net

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - smm-net

  backend:
    build:
      context: ./Back-end
      dockerfile: Dockerfile.dev
    volumes:
      - ./Back-end:/app
    env_file:
      - ./Back-end/.env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - smm-net

  aiservice:
    build:
      context: ./aiService
      dockerfile: Dockerfile.dev
    volumes:
      - ./aiService:/app
    env_file:
      - ./aiService/.env
    depends_on:
      - redis
    ports:
      - "8001:8001"
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    networks:
      - smm-net

  celery-worker:
    build:
      context: ./Back-end
      dockerfile: Dockerfile.dev
    volumes:
      - ./Back-end:/app
    env_file:
      - ./Back-end/.env
    depends_on:
      - backend
    command: celery -A config worker --loglevel=info
    networks:
      - smm-net

  celery-beat:
    build:
      context: ./Back-end
      dockerfile: Dockerfile.dev
    volumes:
      - ./Back-end:/app
    env_file:
      - ./Back-end/.env
    depends_on:
      - backend
    command: celery -A config beat --loglevel=info
    networks:
      - smm-net

  frontend:
    build:
      context: ./Front-End
      dockerfile: Dockerfile.dev
    volumes:
      - ./Front-End:/app
      - /app/node_modules
    env_file:
      - ./Front-End/.env
    ports:
      - "3000:3000"
    command: npm start
    networks:
      - smm-net

volumes:
  postgres_:

networks:
  smm-net:
    driver: bridge